### ISSUE TITLE
来踩个点

### ISSUE THREAD

**Issue by jae-jae** [nondanee/Glee#1]
![qq 20171017195722](https://user-images.githubusercontent.com/5620429/31663702-96adb26a-b375-11e7-9bc0-4e0510348a24.png)

已使用Glee两周的重度用户来踩个点 :_onion_head_blush2:

**Comment by nondanee** [comment]
大更新😣 累死我了

**Comment by nondanee** [comment]
等等，我已经写了两周了？🤔😱

**Comment by nondanee** [comment]
感觉这次commit截的图没你截的好看……😭😭😭
