### ISSUE TITLE
请问会有MV的功能吗？

### ISSUE THREAD

**Issue by zhaowweny** [nondanee/Glee#11]
我看了那个API，发现有MV的功能，希望Glee也能加上。我试了一下，可以拿到MV的详情，但是获取MV地址那块没看太明白，是直接get请求吗？我试了get请求和post请求都拿不到数据，也不清楚返回的数据是什么格式的，看API好像不是json，网页上直接ajax请求又存在跨域问题。我用了几个第三方播放器都没有MV功能，不知道是不是API失效了，如果没有，希望大神可以加上这个功能，谢谢！

**Comment by nondanee** [comment]
抱歉了暂时没时间更新glee
MV地址网易有个[防盗链的措施](https://github.com/Binaryify/NeteaseCloudMusicApi/blob/master/router/mv_url.js)，会检查请求头
感觉比较难实现，单纯浏览器js做不到，只能用node开一个server
我试了下没有失效，`/mv/url?={url}`这个接口获得就是视频数据
