### ISSUE TITLE
关于color thief和cors的问题

### ISSUE THREAD

**Issue by zluo01** [nondanee/Glee#14]
你好，我看到了你用了color thief来提取图片的color，但是假如使用了api里面的url我会出现CORS的问题，导致不能getImageData(). 想问一下你是怎么解决这个问题的？？我看了代码，并没有看到crossOrigin的字眼。。。

谢谢

**Comment by nondanee** [comment]
electron 没有同源策略限制，所以我不需要考虑😂
普通浏览器的话，应该需要后端做一下代理来解决跨域
