### ISSUE TITLE
播放歌曲可以正常被记录吗？

### ISSUE THREAD

**Issue by zhaowweny** [nondanee/Glee#15]
这里面播放歌曲能不能正常被云音乐记录啊，我之前做了一个测试请求几首歌曲都没有被记录。另外发现更新了，求Mac版新包啊^_^

**Comment by nondanee** [comment]
不能，要记录请参考这个，https://github.com/Binaryify/NeteaseCloudMusicApi/pull/431
新版只支持 Windows，其实没什么更新

**Comment by zhaowweny** [comment]
多谢老哥，几个月没关注，Mac版API加密算法都出来了🤣

**Comment by nondanee** [comment]
Mac 版 API ?

**Comment by zhaowweny** [comment]
那个eapi不是Mac版吗？难道是 win版？不过我只看到了加密算法，API应该差不多吧

**Comment by nondanee** [comment]
emmm 我忘了我加进去了，是 macos / windows / android / ios 公用的 API，做请求头比较复杂

**Comment by zhaowweny** [comment]
嗯，抓包发现最新版的Mac版返回的数据乱码，代码里面随机测试一个请求，我用最新版的params参数没有任何数据返回，也没有报错，就和没请求一样，用旧版的参数就能返回数据而且抓包工具还能正常显示，我看请求头应该是一样的。不知道什么原因😂

**Comment by nondanee** [comment]
返回数据加了密的，`e_r: false` 就能取消加密
在原来 params 的基础上要加一个 header，就是 cookie 数据，data.js 最底下有，被备注掉的

**Comment by zhaowweny** [comment]
尝试用纯JS重写你的eapi，引入这个[cryptojs库](https://github.com/zhaowweny/CryptoDemo/blob/master/cryptojs/crypto-js.js)，测试了一下还是没有任何返回数据，也没有报错，是哪里弄错了吗？
`var eapiKey = 'e82ckenh8dichen8';// eapi key`

`function strToHexCharCode(str) {`
      `if(str === "")`
         ` return "";`
      `var hexCharCode = [];`
      `for(var i = 0; i < str.length; i++) {`
          `hexCharCode.push((str.charCodeAt(i)).toString(16));`
      `}`
      `return hexCharCode.join("");`
`}`

`function AesEncrypt(text, secKey) {`
      `var _text = CryptoJS.enc.Utf8.parse(text);`
      `var _secKey = CryptoJS.enc.Utf8.parse(secKey);`
      `var encrypted = CryptoJS.AES.encrypt(_text, _secKey, { iv: '', mode: CryptoJS.mode.ECB});`
      `return encrypted.toString();`
`}`

`function EAPI(path, object) {`
      `var text = JSON.stringify(Object.assign(object, {e_r: 'false'}));`
     `var message = 'nobody'+ path +'use'+ text +'md5forencrypt';`
      `var digest = strToHexCharCode(CryptoJS.MD5(message).toString());`
      `var data = path +'-36cd479b6b5-'+ text +'-36cd479b6b5-'+ digest;`
      `var params = encodeURIComponent(strToHexCharCode(AesEncrypt(data, eapiKey)).toUpperCase());`
      `return {`
          `params: params`
     ` }`
`}`

`function getUserPlaylist(uId) {`
    `var data = {`
        `uid: uId,`
       `limit: 1000,`
       `offset: 0`
    `};`
	`var header = {`
		`"MUSIC_A": `"8aae43f148f990410b9a2af38324af24e87ab9227c9265627ddd10145db744295fcd8701dc45b1ab8985e142f491516295dd965bae848761274a577a62b0fdc54a50284d1e434dcc04ca6d1a52333c9a",
		`"MUSIC_U": "",`
		`"appver": "1.4.1",`
		`"deviceId": "a9474b0f7f5f10f851a7f519f07842d1",`
		`"os": "uwp",`
		`"osver": "10.0.16299.371",`
		`"requestId": "6c30f907-176b-4ca4-8334-d3d2589e641d"`
	`};`
	`data["header"] = JSON.stringify(header);`

      `EAPI("user/playlist", data);`
`}`

`getUserPlaylist(38050391);`

**Comment by nondanee** [comment]
怎么说？

**Comment by nondanee** [comment]
https://codepen.io/nondanee/pen/wNJJyg?editors=0012

- MD5 结果不对
- AES 结果不对
- API Path 不对

```javascript
var eapiKey = 'e82ckenh8dichen8';// eapi key

function AesEncrypt(text, secKey) {
	var _text = CryptoJS.enc.Utf8.parse(text);
	var _secKey = CryptoJS.enc.Utf8.parse(secKey);
	var encrypted = CryptoJS.AES.encrypt(_text, _secKey, { iv: '', mode: CryptoJS.mode.ECB});
	return encrypted.ciphertext.toString().toUpperCase();
}

function EAPI(path, object) {
	var text = JSON.stringify(Object.assign(object, {e_r: 'false'}));
	var message = 'nobody'+ path +'use'+ text +'md5forencrypt';
	var digest = CryptoJS.MD5(message).toString();
	var data = path +'-36cd479b6b5-'+ text +'-36cd479b6b5-'+ digest;
	var params = encodeURIComponent(AesEncrypt(data, eapiKey));
	return {
		params: params
	};
}

function getUserPlaylist(uId) {
	var data = {
		uid: uId,
		limit: 1000,
		offset: 0
	};
	var header = {
		"MUSIC_A": "8aae43f148f990410b9a2af38324af24e87ab9227c9265627ddd10145db744295fcd8701dc45b1ab8985e142f491516295dd965bae848761274a577a62b0fdc54a50284d1e434dcc04ca6d1a52333c9a",
		"MUSIC_U": "",
		"appver": "1.4.1",
		"deviceId": "a9474b0f7f5f10f851a7f519f07842d1",
		"os": "uwp",
		"osver": "10.0.16299.371",
		"requestId": "6c30f907-176b-4ca4-8334-d3d2589e641d"
	};
	data["header"] = header;

	return EAPI("/api/user/playlist", data);
}

console.log(getUserPlaylist(38050391));
```

**Comment by zhaowweny** [comment]
居然全错了😭非常感谢大佬，㊗️新年快乐！

**Comment by nondanee** [comment]
🐷🐷🐷
