### ISSUE TITLE
安装依赖时报错

### ISSUE THREAD

**Issue by TTcheng** [nondanee/Glee#16]
安装依赖时报错，依赖"windows-swca"对于Linux平台应该不是必须的吧
![image](https://user-images.githubusercontent.com/19683420/53075794-05dfe000-3529-11e9-8634-3d6329924bbb.png)

**Comment by TTcheng** [comment]
默认分支dev，，，忘了切分支了

**Comment by nondanee** [comment]
用 windows-swca 实现 fluent design 的亚克力效果，所有 windows only
master 分支我不确定还能不能用
glee 功能不完整，不建议使用，用官方客户端吧

**Comment by TTcheng** [comment]
看起来非常不错，就是想尝试下。刚刚切了master分支，npm start还是可以使用的，但是打包失败了。我是一个Java后端程序员，总感觉做前端很厉害，做出来的东西都很酷。
