### ISSUE TITLE
窗口拖动速度奇慢

### ISSUE THREAD

**Issue by wutong233** [nondanee/Glee#21]
拖动时看起来就像是慢动作一样慢慢地彳亍，但是实际上窗口早就到了鼠标拖到的位置了
还有左边所有按钮都没反应，用的npm start

**Comment by nondanee** [comment]
知道的，开了亚克力效果就会这样
你可以给 window-swca 提 issue，不过提了应该也没用，它也是直接调微软的 api

左边都没实现，README 里也没写有这些功能
