### ISSUE TITLE
关于npm install

### ISSUE THREAD

**Issue by Kutius** [nondanee/Glee#22]
是需要VS的组件吧？

**Comment by JasonKhew96** [comment]
node?
https://nodejs.org/en/

**Comment by Kutius** [comment]
> node?
> https://nodejs.org/en/

是12.16.3的版本

**Comment by JasonKhew96** [comment]
`Glee` 目录里执行 `npm install`
![image](https://user-images.githubusercontent.com/29531167/82215440-02b0eb00-994a-11ea-9f73-12c3cc52219d.png)

**Comment by nondanee** [comment]
@Gaaraly 
有 gyp 的依赖，但是写到 optionalDependencies 里了，报错应该不影响吧？还是可以启动的

**Comment by Kutius** [comment]
> `Glee` 目录里执行 `npm install`
> ![image](https://user-images.githubusercontent.com/29531167/82215440-02b0eb00-994a-11ea-9f73-12c3cc52219d.png)

![image](https://user-images.githubusercontent.com/43736711/82218101-f464ce00-994d-11ea-9602-d8765a329468.png)
像这样

**Comment by nondanee** [comment]
- 可以启动 > 直接启动 (无亚克力效果)
- 不可以启动
    - 想看亚克力效果 > 装 VS
    - 不用看亚克力效果 > package.json 里移除 windows-swca

建议不用折腾了，直接放弃
基本功能都没做，就好看好看

**Comment by Kutius** [comment]
> * 可以启动 > 直接启动 (无亚克力效果)
> * 不可以启动
>   
>   * 想看亚克力效果 > 装 VS
>   * 不用看亚克力效果 > package.json 里移除 windows-swca
> 
> 建议不用折腾了，直接放弃
> 基本功能都没做，就好看好看

明白了，感谢！😺
不胜叨扰
