### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by Anstrisk** [nondanee/Glee#23]
打扰了，我没学过node.js，按照Readme的方法编译无法通过，项目代码和release代码提示两种不同错误，上网无法找到正确解决方法
https://user-images.githubusercontent.com/56513329/82667178-e2df3700-9c69-11ea-9b2c-a255711bb62d.png

**Comment by Anstrisk** [comment]
另一个错误是在python的那一步失败的，虽然可以打包成功，但是只有主界面生效，其他的都无反应。

**Comment by nondanee** [comment]
你切 dev 分支试下吧，master 应该不会维护了，release 也是 master 的

你说的只有主界面生效，其他都无反应是说侧边栏吗？因为其他压根就没写 😂

**Comment by Anstrisk** [comment]
> 你切 dev 分支试下吧，master 应该不会维护了，release 也是 master 的
> 
> 你说的只有主界面生效，其他都无反应是说侧边栏吗？因为其他压根就没写 😂

啊，那个应该是无法联网，界面一片空白
至于另一个，仔细看了一下报错的地方，好像是python的版本问题，换成python2.7就成功了，感谢，加油💪

**Comment by Anstrisk** [comment]
> 你切 dev 分支试下吧，master 应该不会维护了，release 也是 master 的
> 
> 你说的只有主界面生效，其他都无反应是说侧边栏吗？因为其他压根就没写 😂

修改user文件的ID，登录成功了😂

**Comment by nondanee** [comment]
emmm 好像 gyp 模块很难 build 的样子，我试试看搞个 ci 吧

不是很想写，随缘吧，感觉用官方客户端也挺好的

那个不是登录哦，只能获取你公开的歌单

**Comment by nondanee** [comment]
加上 CI 了，可以在 Artifacts 里下载到哦
https://github.com/nondanee/Glee/actions/runs/113255049

**Comment by Anstrisk** [comment]
> 加上 CI 了，可以在 Artifacts 里下载到哦
> https://github.com/nondanee/Glee/actions/runs/113255049

谢谢！
