### ISSUE TITLE
列表太长了

### ISSUE THREAD

**Issue by jae-jae** [nondanee/Glee#3]
![111](https://user-images.githubusercontent.com/5620429/31802349-5642a80e-b580-11e7-81c4-74d459390a8f.gif)
如图，列表太长了，能固定高度，来个滚动条不？

**Comment by nondanee** [comment]
emmmm，itunes里面就是这样的
看到不喜欢的歌单不是应该向前滚点它封面把它收起来嘛=。=
咋还向继续后滚，实话说应该也不会影响，你展开底下另一的时候这个会收起来
可以考虑，主要是滚动条样式很难选，默认的贼丑我给全局隐藏了
看效果吧，设个max-height还是蛮方便的 ~ 
个人倾向是不改，然后把收起导致的高度改变用滚动补偿剪掉

**Comment by cyang812** [comment]
右边应该有一条滑动栏

**Comment by nondanee** [comment]
@cyang812 意思也是固定高度然后可以滚动吗？主要是滚动条样子难看啊，不像手机上的滚动条不移动会自动隐藏~
而且二级滚动可能滚动里面的时候多滚，就把外面滚飞了

**Comment by nondanee** [comment]
@jae-jae @cyang812 
![_2017_10_23_01_03_41_408](https://user-images.githubusercontent.com/26399680/31864344-48f499cc-b78e-11e7-9773-c7378a6ad36d.gif)
这样可以么？

**Comment by jae-jae** [comment]
赞👍

**Comment by cyang812** [comment]
font{
        line-height: 1.7;
    }


    
这样子挺好的



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

            
                
            



    在2017年10月23日 01:06，Nzix<notifications@github.com> 写道： 


@jae-jae @cyang812

这样可以么？

**Comment by cyang812** [comment]
这样挺好的
