### ISSUE TITLE
可以设置代理吗

### ISSUE THREAD

**Issue by HeFanFrog** [nondanee/Glee#4]
大佬，公司网络走代理的，直连不通-_-
可以设置代理吗

**Comment by nondanee** [comment]
我研究了下
你要改两个地方
1. [main.js](https://github.com/nondanee/Glee/blob/master/main.js)
你在头上找个位置加上
```app.commandLine.appendSwitch('proxy-server', '127.0.0.1:1080')```

2. [js/data.js](https://github.com/nondanee/Glee/blob/master/js/data.js)
第703行
原来```const request = require('request')```
改成```const request = require('request').defaults({'proxy':'http://127.0.0.1:1080'})```

具体ip和端口号你自己写

**Comment by HeFanFrog** [comment]
🙏大佬，回去试下
