### ISSUE TITLE
执行“npm run package-win”时出现错误

### ISSUE THREAD

**Issue by CXZS-Git** [nondanee/Glee#6]
![image](https://user-images.githubusercontent.com/3448255/32871319-4a3516fa-cabb-11e7-807e-7d78f32c2b22.png)

全局代理也依然无法连接。

**Comment by nondanee** [comment]
那就换源试试吧
```
npm config set registry https://registry.npm.taobao.org/
npm config set electron_mirror https://npm.taobao.org/mirrors/electron/
```

**Comment by CXZS-Git** [comment]
换源之后速度非常快。
非常感谢。

**Comment by CXZS-Git** [comment]
题外话：为什么taobao.org不能被解析，jm.taobao.org就能被解析呢？解析顺序不应该是org→taobao→jm嘛...

**Comment by nondanee** [comment]
没记错的话
```
taobao.org
???.taobao.org
```
都属于解析A类记录
没有前缀的叫主域名
另一个是子(二级)域名
这两条记录是并列关系
不是包含关系
可以单独指向不同ip(没有指向也行)
有兴趣的话可以买个域名试一下

**Comment by CXZS-Git** [comment]
大致明白了，而且有了关键词可以再搜索了解下。
Thanks！

**Comment by nondanee** [comment]
@weiyichen2011 之前泛解析和主域名弄混了，已经改正
域名解析控制台是这个样子，每一行都可以单独修改和删除，相互直接没有关系
![sshot-1](https://user-images.githubusercontent.com/26399680/32926378-e0ca0050-cb81-11e7-8291-6201cd8b4f2e.png)
像taobao.org不解析而jm.taobao.org可以解析，只要把主域名那行删掉，只留下子域名的规则就行了

**Comment by CXZS-Git** [comment]
懂了，感谢解答。

**Comment by nondanee** [comment]
👌客气了

**Comment by CXZS-Git** [comment]
你人真好（笑。
