### ISSUE TITLE
无管理员权限的情况下无法关闭窗口

### ISSUE THREAD

**Issue by CXZS-Git** [nondanee/Glee#7]
Windows 7，普通用户帐户权限打开后无法正常关闭窗口，仅能通过任务管理器强行结束。
管理员权限可以正常关闭。

**Comment by nondanee** [comment]
偶尔无法关闭窗口这个是已知bug，而且我无法解决，release那边就有标注了
刚在Win 7 x86上测试了，也是偶尔发生，1/15吧，基本都能关闭
应该与管理员权限无关
如果点×关闭不了
可以试试标题栏右键，有可能需要点两次，emmm
![cl](https://user-images.githubusercontent.com/26399680/33302944-bef03640-d43a-11e7-8e0c-f992c8db2749.png)

**Comment by CXZS-Git** [comment]
( ・_ゝ・)
好吧，不用管理员权限确实也能关闭，看来是我脸黑刚下载下来那会就关不掉...

**Comment by nondanee** [comment]
emmm下载的？release那个？一直没更新，那个bug可多了😂自己打包吧

**Comment by CXZS-Git** [comment]
OK，我在自己的笔记本上是按照reademe的步骤打包的，在公司的电脑上没有运行环境还要装嫌麻烦来着...
